#!/bin/zsh
bison -o Analysis.cpp -d Analysis.y
flex -o lex.cpp Analysis.l
g++ ../../MiniSQL.cpp Analysis.cpp ../SQLGrammarTree.cpp ../../API/API.cpp ../../CatalogManager/CatalogManager.cpp -o parser  

